#!/bin/bash

current_home=$(cd `dirname $0`;pwd)
. ${current_home}/check $@
[ $? != 0 ] && exit

if [ "" == "$3" ] || [ "$(echo "$3"|egrep -v '^[0-9]+$')" != "" ]; then
    lines=10
else
    lines=$3
fi

los_info=`tail -${lines} ${EOS_LOG}`
echo "$(hostname) --> ${los_info}"